apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-app
  namespace: argocd
spec:
  project: default
  
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  source:
    repoURL: https://github.com/safernandez666/GithubGitOps.git
    targetRevision: HEAD
    path: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

