apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
  namespace: sample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
        - name: static-app-container
          image: safernandez666/app:bfb90c4e04e8038c1839b47bd20115d6dd419330
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: static-app
