apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
  namespace: sample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
        - name: static-app-container
          image: safernandez666/app:4d20cc2286b7a4f98b444ec6afd2de3e0f9ffeb4
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: static-app
