apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-app-ingress
  namespace: sample
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
<<<<<<< HEAD
    - host: dev.static-app.com
=======
    - host: dev.sample-app.com
>>>>>>> 783ffa27ad66b1cf63069e6e4563c079baafa973
      http:
        paths:
          - path: /
            pathType: Prefix  
            backend:
              service:
                name: static-web-service
                port:
                  number: 80