apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-app-ingress
  namespace: sample
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: 192-168-205-129-nip-io-tls
      hosts:
        - '*.192.168.205.129.nip.io'
  rules:
    - host: dev.192.168.205.129.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix  
            backend:
              service:
                name: static-web-service
                port:
                  number: 80