name: Repository Dispatch
on:
  repository_dispatch:
    types:
      - my-custom-event
jobs:
  handle-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print commit hash
        run: echo ${{ github.event.client_payload.sha }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}